### ISSUE TITLE
同率10位とイレギュラーデータの合計が30件以上あると意図しないランキングツイートをしてしまうと思われる

### ISSUE THREAD

**Issue by nobby451** [roudai/IdolitterTS#18]
https://github.com/roudai/IdolitterTS/blob/4ada72def8ed7eba95fadd3f415e4e76ca6848ba/src/daily-analysis.ts#L248
取得している差分は2～30の29件に対し、
https://github.com/roudai/IdolitterTS/blob/4ada72def8ed7eba95fadd3f415e4e76ca6848ba/src/daily-analysis.ts#L254
ループを回す回数が0～29の30件であるため、もしイレギュラーデータの頻発や同率10位が続いてループが最後まで到達してしまうと、最終ループで配列から添字で取る変数がundefinedとなってしまいます。
undefinedは文字列と連結するとそのまま'undefined'という文字列となってしまうので、'10位 undefined人 undefined'みたいな文字列となると思われます。

ループを回すときは終了条件にArray.prototype.lengthを使うか、Array.prototype.forEachなどのループ関数を使うのがいいかと思います。

**Comment by roudai** [comment]
lengthを使うよう修正しました。
