### ISSUE TITLE
イレギュラーデータによってはランキングが同率じゃないのに同率と判定される場合がある

### ISSUE THREAD

**Issue by nobby451** [roudai/IdolitterTS#19]
フォロワー増加数がA: 100, B: 100, C: 90という3人のアイドルがいるとします。
AとCは増加率8倍未満で正常データで、Bは増加率8倍以上でイレギュラーデータとします。
最初のループでAは1位となり、次のBは数は同率なので`rankup`だけインクリメントして`rank`はそのままです。
2回目のループではBはイレギュラーデータなので、`continue`され次のループに進みます。
3回目のループではCはAより増加数が少ないにも関わらず、1位としてツイートされます。

イレギュラーデータを弾いて`continue`する前にも同率順位処理をする必要があると思います。

**Comment by roudai** [comment]
思ったより根が深いのと、ほぼ起こりえないパターンなので一旦放置します。

**Comment by nobby451** [comment]
実装を考えるとすれば、前の順位の増加数を変数に保存しておき、`nextRankTweet`を構築する直前で`rank`と`rankup`処理を行い、増加数を更新でしょうか。
根が深いと思われてるのはツイート140文字オーバーでループが巻き戻る関係だと推測しますが、ここの`else`で`tweet`に`title`と`nextRankTweet`を代入して次のツイートを構築をしてしまえば、ループを巻き戻す必要はありません。
ループの最中でループ変数を巻き戻すのも、バグを生みやすいので控えたほうがいいと思います。

滅多に起こりえない現象というのはその通りだと思うので、保留もしくは却下しても問題ないレベルとは思います。

**Comment by nobby451** [comment]
すみません。操作ミスで一瞬勝手にクローズしてしまったので再オープンしました。
