### ISSUE TITLE
卒業脱退予定の14日後が今日より前のデータがあると、無関係のデータが削除される可能性がある

### ISSUE THREAD

**Issue by nobby451** [roudai/IdolitterTS#25]
https://github.com/roudai/IdolitterTS/blob/77191379a439e3977f706080d142eae2c3ead62e/src/auto-delete.ts#L34
卒業脱退予定の14日後が今日より前が`true`になるということは、
https://github.com/roudai/IdolitterTS/blob/77191379a439e3977f706080d142eae2c3ead62e/src/auto-delete.ts#L26
卒業脱退予定日も今日より前ということになるので、両方の`if`の条件を満たしてしまい、本来削除されるはずだった行の1個下も巻き添えで削除されるのではないかと思います。
恐らく各`if`は同時に満たされることはない想定と思われるので、`else if`で繋げるか、`if`の最後に`return`するのがいいかと思います。

すみません。酔ってて変なところで送信してしまいました。

**Comment by roudai** [comment]
ifが排他的ではないことの認識はあったんですが、なんかいけそうな気がしてました。
修正しました。
