### ISSUE TITLE
TwitterIDのリンク追加処理でArray.prototype.mapのコールバック引数をあり得ない型に強制している

### ISSUE THREAD

**Issue by nobby451** [roudai/IdolitterTS#28]
https://github.com/roudai/IdolitterTS/blob/e43699c9706834d1d6b81936e564d3c2f050220b/src/check-account.ts#L20
ここのコールバック関数の引数`value`ですが、`GoogleAppsScript.Spreadsheet.Range.getValues()`の戻り値の型は`any[][]`なので、`value`は本来`any[]`に推論され、`string`にはなり得ません。
タチの悪いことに`string`も`Array`もどちらも`indexOf`関数を持っているため、ランタイムではエラーにはならないのに意図と異なる挙動になるという発見しづらいバグの原因となりえます。

今回のようなミスはTypeScriptの型チェックや型推論を使うことで、静的解析によって検出が可能なので、TypeScriptの活用を強く推奨します。

なお、`any[]`に推論されるのも十分ガバなんですが（せめて`number | boolean | Date | string`のUnionにしろと言いたい）、`value`を`string[]`に強制するのは`any[]`に反していないのでアリです。

**Comment by roudai** [comment]
型推論だと string | string[] になりました。string[] にしました。
https://github.com/roudai/IdolitterTS/commit/a80878f687dde05705f7ca77d7cc7f9e0fc1e0a2

**Comment by nobby451** [comment]
https://github.com/roudai/IdolitterTS/blob/9c5b2d25a1efc6807c2e7e214c6f3c47b5a6b1f7/src/check-account.ts#L5
残念ですが、ここで`dataSheet`を`any`と宣言している時点でそこからメソッドで取り出せる全ての変数に`any`が伝播してしまうので、`map`関数のコールバック引数の型推論が効くことはありません。
`string | string[]`に推論されているとしたらそれは勘違いです（そもそも`string`にはなりえません）。

`dataSheet`の正しい型は`GoogleAppsScript.Spreadsheet.Sheet`もしくは、`GoogleAppsScript.Spreadsheet.Sheet | null`です。
`null`とのUnionにするかどうかは、シートが見つからない場合の例外処理をクラスの中で行うか外で行うかの違いです。
この型定義は、ファイルの先頭で
``` ts
import 'google-apps-script/google-apps-script.spreadsheet';
```
と書くと使えるようになります。
このファイルは型定義ファイルで関数や変数などの実態を持たないので、ビルドされたらバンドルされることはなく単純に消え去ります。

**Comment by roudai** [comment]
なるほど、確かにimportすることでSheet型が使えるようになりました。
https://github.com/roudai/IdolitterTS/commit/8cc2dbf9142fc9de6bdf8259293b585fae1c4f94

**Comment by roudai** [comment]
ちなみに、ローカル環境だとdayjsとかTwitterClientがずっとエラーになるんですが、これを解消する方法ってあるんですかね？

**Comment by nobby451** [comment]
とりあえず`dayjs`の方はそれらしい解決方法が見つかりました。
ポイントとしては、
- GASによってグローバル変数として`dayjs`が供給される
- モノとしてはnpmで入れられる`dayjs`と同じ
- ただし、グローバル変数`dayjs`の1階層下に`dayjs`というプロパティが存在し、それがnpmで入れられる`dayjs`に相当

npmの`dayjs`が有効活用できそうなのでまずは入れていきましょう。
```
$ npm i -D dayjs
```
`dayjs`は大元のパッケージに型定義ファイルも含まれているので、型定義ファイルだけがほしい場合でも全体を追加する必要があります。
`dayjs`は普通は`-P`オプションでインストールしますが、ここでは型定義がほしいだけなので`-D`オプションでいいでしょう。
ここで安易に
``` ts
import dayjs from 'dayjs';
```
とかやってしまうと、npmの`dayjs`をスクリプトに取り込むことになりますし、そもそもシグネチャーが違います。
ではどうするかというと、
適当なファイル名（例：dayjs.ts）で以下のファイルを作成してください。
``` ts
import _dayjs from 'dayjs';

declare global {
  // eslint-disable-next-line no-var
  var dayjs: {dayjs: typeof _dayjs};
}
```
`declare global`でグローバル空間に暗黙に存在する変数を定義できます。
この変数はスクリプト内では実体を持たず、GASによって供給されるのを前提として型定義情報のみを持ちます。
この`dayjs`の型は、それ自身は`object`型であり、『npmの`dayjs`の`default export`型』の`dayjs`というプロパティを持ちます。
`typeof`はJavaScriptにおいては変数の型を`string`で返す単項演算子ですが、TypeScriptにおいては、文脈によっては`type`を返します。
ここにおいてはTypeScript的な型が期待される場所なので`type`が返されます。
`default export`の`import`名を`_dayjs`にしているのは`dayjs`だと定義したいグローバル変数と同じだから変えているだけです。もちろんこれは何でも構いません。
`const`ではなく`var`使っているのは、`declare`でグローバル変数を定義するときは`var`を使うのがお作法だからだそうです。ESLintが現状それの判断をできないので、禁じ手の`eslint-disable`を使います。

定義の作成までできたので、次は使用する側です。
ファイル名がdayjs.tsの場合、`dayjs`を使っているtsファイルの中で、
``` ts
import './dayjs';
```
とします。
`'dayjs'`だけだと`node_modules`の`dayjs`を参照することになるので、`'./dayjs'`としてください。
これを取り込むことでグローバル変数に型情報を与えることができるのでエラーは消えると思います。

`TwitterClient`に関してはすみません。どこに型定義があるか見つけられず、解決方法がわかりません。
npmに存在するのなら教えていただければ対応は可能かと思います。
あまり考えづらいことですが、もしnpmに型定義が存在しない場合、自分で型定義ファイルを作成することになるかもしれません。

はっきり言って自分はTypeScript初学者なので、`dayjs`の方も間違っているか、もしくは筋が悪い可能性も高いです。
もしろーだいさんの周りにTypeScriptの熟練者がいれば、その方に聞いたほうが良質な回答が得られるのではないかと思います。
