### ISSUE TITLE
スクリプトプロパティの状態によってはMailApp.sendEmailに'null'という文字列をメールアドレスとして渡してしまう

### ISSUE THREAD

**Issue by nobby451** [roudai/IdolitterTS#29]
https://github.com/roudai/IdolitterTS/blob/df16c393ee1f91f7928867e3edf46be27b28abe1/src/check-error.ts#L10
`getProperty`はキーが存在しない場合には`null`を返すので、スクリプトプロパティに`'email'`というキーが存在しなければ、`String`コンストラクターに`null`を渡してしまい、`'null'`という文字列が返されます。
IOが関わる部分においては、本当にその外部リソースが存在するかどうかはランタイムにしかわからないので、静的解析上では普通存在しない場合が考慮されます（今回の場合戻り値の型が`string | null`になる）。
考えられる対応は3つあります。

1. エラーチェックをする
`this.recipient`は`string | null`として、`null`だった場合はエラーとしてスクリプトの実行を止めるなどです。
ただ、このクラスの目的がシートの状態がおかしい場合の通知なので、ただプログラムが停止するのでは都合が悪いと思います。

2. デフォルト値を設定する
`PropertiesService.getScriptProperties().getProperty('email') ?? 'report@example.com'`のようにすると、キーが存在しない場合に`'report@example.com'`をデフォルト値として使います。
`??`はnull合体演算子といい、左辺が`null`または`undefined`と評価された場合は右辺を返し、それ以外の場合は左辺を返します。

3. Non-null assertionを使う
スクリプトプロパティは存在しない可能性があるとはいえ、自分で完全に制御が可能なので必ず存在することを保証することは可能です。
`PropertiesService.getScriptProperties().getProperty('email')!`とすると、戻り値の型が`string | null`から`string`になり、TypeScriptの型チェックシステムに対しnullにはなり得ないことを教えることができます。
コードが示す意図の問題になりますが、`String`で変換の場合は`null`でも文字列`'null'`に変換すれば正常動作という意味になりますので、`null`が来たら明確に異常動作であると示せるNon-null assertionの方がより適していると思います。
（この規模のプログラムであれば、恐らく`null`を渡しても`'null'`を渡しても`MailApp.sendEmail`でエラーになると思うので不具合箇所は一目瞭然ですが、複雑になるとこの差が効いてきます）

なお、`SpreadsheetApp.getActiveSpreadsheet().getSheetByName`の場合も、シート名が存在しない可能性があるので、同様の問題が発生しています。

**Comment by nobby451** [comment]
すみません。書いてる最中に`GoogleAppsScript.Spreadsheet.Sheet | null`に関しては対応されてましたね（遅筆マン参上）。

**Comment by roudai** [comment]
nullの場合はエラーログを出すよう修正しました。
https://github.com/roudai/IdolitterTS/commit/d1240665543029bbc71cc4a934f90ac06b4a736c
