### ISSUE TITLE
グループ名に正規表現における特殊文字が含まれると意図しない結果になると思われる

### ISSUE THREAD

**Issue by nobby451** [roudai/IdolitterTS#36]
https://github.com/roudai/IdolitterTS/blob/c94fd1fa5e5fe98db1acc2f586bdba710d815030/src/common.ts#L8
`String.prototype.match()`は、引数が正規表現オブジェクト以外の場合、与えられた引数を内部で`new RegExp`で正規表現オブジェクトに変換して処理するので、グループ名に正規表現における特殊文字が含まれていると、意図しない結果になる場合があるのではないかと思われます。
単純にアイドル名の中にグループ名が含まれているかどうかを判定するのであれば、`String.prototype.indexOf()`または`String.prototype.includes()`を使うのがいいのではないかと思います。
ここでは一致した位置はいらなさそうなので、`boolean`を返す`includes`がより適切かと思います。

**Comment by roudai** [comment]
`match`を`includes`に変更しました。
https://github.com/roudai/IdolitterTS/commit/e3a5f6602ece3d508c429b4803549a63882ac32d
